<!DOCTYPE html>
<html>
    <head>
    	
       <link rel="stylesheet" href="./css/style1.css" type="text/css"/>
      <link rel="stylesheet" href="./css/bootstrap.css" type="text/css" />
         <link rel="stylesheet" href="./css/listsanpham.css" type="text/css">
         <meta http-equiv="content-type" content="text/http; charset=UTF-8">
          <script src="jquery.js"></script>
           <script type="text/javascript" src="slider.js"></script>  
           <title><?php echo $page_title; ?></title> 
   </head>